### ISSUE TITLE
Use real git tags to ease changelog understanding

### ISSUE THREAD

**Issue by rjanot** [Champii/Nodulator#7]
Hi,

A friend of you, Allan, asked me to check your work. First of all congrats, because it's a huge project.

When checking changelog, I saw that you don't have any git tags on the project. It's really useful

**Comment by Champii** [comment]
Thank you for your advices, it's a project that use all my free time and I don't have so much reviews :)

About tags, I thought that git flow could have made them automaticaly...
I will see further to incorporate them from now !

**Comment by rjanot** [comment]
You're welcome

Maybe they are only on you local repository ?

Do you see tags when you do `git tag` ? if so you can do a `git push origin master --tags`

**Comment by Champii** [comment]
Oh my god I feel so stupid...

You made my day, I was wondering how to make that !
Fixed !

**Comment by rjanot** [comment]
:+1:
